name: Snyk Analysis
env:
  DOTNET_VERSION: '8.x'                     # la versi칩n de .NET
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      - name: Configurando la versi칩n de NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}  
      - name: Snyk monitor
        run: snyk code test --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}          
      - name: Install snyk-to-html
        run: npm install -g snyk-to-html  # Instalar snyk-to-html si no est치 disponible
      - name: Generate HTML report
        run: snyk-to-html -o snyk-report.html < snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4  # Actualizado a la versi칩n v4
        with:
          name: snyk-report
          path: snyk-report.html
